// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATransfer: typeof import('ant-design-vue/es')['Transfer']
    Bg: typeof import('./../src/components/Root/Bg.vue')['default']
    BuffCrawler: typeof import('./../src/components/Crawler/BuffCrawler.vue')['default']
    copy: typeof import('./../src/components/Crawler/DataAnalyser copy.vue')['default']
    CrawlerList: typeof import('./../src/components/Root/Player/CrawlerList.vue')['default']
    CustomTitleBar: typeof import('./../src/components/Root/CustomTitleBar.vue')['default']
    DataAnalyser: typeof import('./../src/components/Crawler/DataAnalyser.vue')['default']
    'DataAnalyser copy': typeof import('./../src/components/Crawler/DataAnalyser copy.vue')['default']
    Dialog: typeof import('./../src/components/Root/Player/Dialog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Menu: typeof import('./../src/components/Root/Navigator/Menu.vue')['default']
    PurchaseAnalyser: typeof import('./../src/components/Crawler/PurchaseAnalyser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./../src/components/Root/SideNav.vue')['default']
    UserCenter: typeof import('./../src/components/Root/Player/UserCenter.vue')['default']
  }
}
