// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CrawlerList: typeof import('./src/components/Root/Player/CrawlerList.vue')['default']
    CustomTitleBar: typeof import('./src/components/Root/CustomTitleBar.vue')['default']
    Dialog: typeof import('./src/components/Root/Player/Dialog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCenter: typeof import('./src/components/Root/Player/UserCenter.vue')['default']
  }
}
